In [4]:
pip install quandl


Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [65]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.model_selection import ShuffleSplit
from sklearn import preprocessing
from sklearn.model_selection import cross_validate
from sklearn.pipeline import make_pipeline
from sklearn.metrics import recall_score
from sklearn.metrics import make_scorer
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import LeavePOut
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.model_selection import GroupKFold
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.model_selection import LeavePGroupsOut
from sklearn.model_selection import GroupShuffleSplit
from sklearn.model_selection import TimeSeriesSplit




X, y = datasets.load_iris(return_X_y=True)
X.shape, y.shape
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0)

X_train.shape, y_train.shape
X_test.shape, y_test.shape

clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, X, y, cv = 10)
scores

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() *2))

scores = cross_val_score(
    clf, X, y, cv=5, scoring='f1_macro')

scores

n_samples = X.shape[0]
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
cross_val_score(clf, X, y, cv=cv)


def custom_cv_2folds(X):
    n= X.shape[0]
    i=1
    while i<=2:
        idx = np.arange(n * (i-1) / 2, n * i / 2, dtype=int)
        yield idx, idx
        i += 1
        
custom_cv = custom_cv_2folds(X)
cross_val_score(clf, X, y, cv=custom_cv)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test)
clf.score(X_test_transformed, y_test)

clf = make_pipeline(preprocessing.StandardScaler(), svm.SVC(C=1))
cross_val_score(clf, X, y, cv=cv)


scoring = ['precision_macro', 'recall_macro']
clf = svm.SVC(kernel='linear', C=1, random_state=0)
scores = cross_validate(clf, X, y, scoring=scoring)
sorted(scores.keys())
scores['test_recall_macro']

scoring = {'prec_macro': 'precision_macro',
          'rec_macro': make_scorer(recall_score, average='macro')}
scores = cross_validate(clf, X, y, scoring=scoring,
                       cv=5, return_train_score=True)
sorted(scores.keys())
scores['train_rec_macro']


scores = cross_validate(clf, X, y,
                       scoring='precision_macro', cv= 10,
                       return_estimator=True)
sorted(scores.keys())

X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):
    print("%s %s" % (train, test))
    
X = np.array([[0., 0.], [1., 1.], [-1., -1.], [2., 2.]])
y = np.array([0, 1, 0, 1])
X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]


print("")
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 12883823
rkf = RepeatedKFold(n_splits= 2, n_repeats=2, random_state=random_state)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))

print("one variable used for testing")
X = [1,2,3,4]
loo=LeaveOneOut()
for train, test in loo.split(X):
    print("%s %s" % (train, test))
    
print("removing p samples")    
X = np.ones(4)
lpo = LeavePOut(p=2)
for train, test in lpo.split(X):
    print("%s %s" % (train, test))
    
print("shuffle and split")    
X = np.arange(10)
ss = ShuffleSplit(n_splits=5, test_size=0.25, random_state=0)
for train_index, test_index in ss.split(X):
    print("%s %s" % (train_index, test_index))
    
print("same percentage of samples of each target class as the complete set")
X, y = np.ones((50, 1)), np.hstack(([0] * 45, [1] * 5))
skf = StratifiedKFold(n_splits=3)
for train, test in skf.split(X, y):
    print('train - {}  | test _ {}'.format(
    np.bincount(y[train]), np.bincount(y[test])))
    
kf = KFold(n_splits=3)
for train, test in kf.split(X, y):
    print('train - {}  | test - {}'.format(
    np.bincount(y[train]), np.bincount(y[test])))
    
    
print("ensures the same group is not represented in both testing and training sets")
print("prevents overfitting due to person specific data")
X = [0.1, 0.2, 2.2, 2.4, 2.3, 4.55, 5.8, 8.8, 9, 10]
y = ["a", "b", "b", "b", "c", "c", "c", "d", "d", "d"]
groups = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3]
gkf = GroupKFold(n_splits=3)
for train, test in gkf.split(X, y, groups=groups):
    print("%s %s" % (train,test))
    
print("cross validation based on different experiments")
print("training set of all samples of the experiment except one")

X = [1,5,10, 50, 60, 70, 80]
y=[0,1,1,2,2,2,2]
groups = [1, 1, 2, 2, 3, 3, 3]
logo = LeaveOneGroupOut()
for train, test in logo.split(X, y, groups=groups):
    print("%s %s" % (train, test))

    
    
    
print("removes P groups for each training/test set")

X = np.arange(6)
y = [1, 1, 1, 2, 2, 2]
groups = [1, 1, 2, 2, 3, 3]
lpgo = LeavePGroupsOut(n_groups = 2)
for train, test in lpgo.split(X, y, groups=groups):
    print("%s %s" % (train, test))
    
print(" Group Shuffle Split generates a sequence of randomize partitions")
print('subset of groups are held out for each split')
X = [0.1, 0.2, 2.2, 2.4, 2.3, 4.55, 5.8, 0.001]
y = ["a", "b", "b", "b", "c", "c", "c", "a"]
groups = [1, 1, 2, 2, 3, 3, 4, 4]
gss = GroupShuffleSplit(n_splits=4, test_size=0.5, random_state=0)
for train, test in gss.split(X,y, groups=groups):
    print("%s %s" % (train, test))
  

print("variation of k-fold which returns first k folds as train set")
print("and k+1th fold as test set")
X = np.array([[1,2], [3,4], [1,2], [3,4], [1, 2], [3, 4]])
y = np.array ([1,2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)
for train, test in tscv.split(X):
    print("%s %s" % (train, test))
    







Accuracy: 0.97 (+/- 0.09)
[2 3] [0 1]
[0 1] [2 3]

[2 3] [0 1]
[0 1] [2 3]
[0 2] [1 3]
[1 3] [0 2]
one variable used for testing
[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]
removing p samples
[2 3] [0 1]
[1 3] [0 2]
[1 2] [0 3]
[0 3] [1 2]
[0 2] [1 3]
[0 1] [2 3]
shuffle and split
[9 1 6 7 3 0 5] [2 8 4]
[2 9 8 0 6 7 4] [3 5 1]
[4 5 1 0 6 9 7] [2 3 8]
[2 7 5 8 0 3 4] [6 1 9]
[4 1 0 6 8 9 3] [5 2 7]
same percentage of samples of each target class as the complete set
train - [30  3]  | test _ [15  2]
train - [30  3]  | test _ [15  2]
train - [30  4]  | test _ [15  1]
train - [28  5]  | test - [17]
train - [28  5]  | test - [17]
train - [34]  | test - [11  5]
ensures the same group is not represented in both testing and training sets
prevents overfitting due to person specific data
[0 1 2 3 4 5] [6 7 8 9]
[0 1 2 6 7 8 9] [3 4 5]
[3 4 5 6 7 8 9] [0 1 2]
cross validation based on different experiments
training set of all samples of the experiment except one
[2 3 4 5 6] [0 1]
[0 1 4 5 6]

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


((90, 4), (90,))